Add redux store
Movgto/react-redux-bookstore pull request #2
Opened 2023-08-28 22:59 UTC by Movgto

# Features:
- Add redux store that links the application react components directly to a single source `store` that stores all the states, reducers, and actions, with this avoiding `prop drilling`, which makes managing the updates for the state much easier than before.
- Add `bookSlice.js`, which contains the state for the `Book` component, and the reducers and actions to perform changes in this state and re-render the corresponding components, this is imported in `store.js` to build the general state of the application.

2023-08-29 02:15 UTC, FrederickMih reviewed
## Hi :raising_hand: :raising_hand: @Movgto, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

The unnecessary **Live Demo** header in the readme file should have been remove to render your readme file simple

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-08-29 18:01 UTC, mikethreels requested changes
Hi Gumaro, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- good job setting up the store

## Required Changes ♻️
- [ ] the structure of the files should follow the ducks pattern this means that the files regarding redux should be in a redux folder in the src folder.
- [ ] there should be a categoryslice.js for redux as well according to the requirements.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-29 18:01 UTC, mikethreels commented on README.md
>  To get a local copy up and running, follow these steps.
- [ ] the link to your MIT license is not working as intended please make sure it is working as shown in the template.

2023-08-29 18:52 UTC, Movgto commented on README.md
>  To get a local copy up and running, follow these steps.
Hi @mikethreels the link is not working because the MIT licence is not in this branch, but it's on the dev branch, so it's going to work once this branch gets merged to the dev branch 😞

2023-08-30 14:37 UTC, joel-kalema approved these changes
Hi @Movgto 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Congratulations! 🎉 

![ ](https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)
## Highlights

The project is running successfully 👍 
PR is well descriptive 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@joel-kalema** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-30 14:42 UTC, merged